{% set name = "album-gui" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a487d5fd14b0973d250002e014c8c75501e6374d71b34de254111c2511269079

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - pip
    - python >=3.7
    - album >=0.9.2
    - pyqt >=5.15.6
    - pywin32-on-windows >=0.1.0

test:
  imports:
    - album.gui
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://album.solutions
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Album is a framework for unifying computational tools across frameworks, languages, and environments. This package provides a graphical user interface for Album.
  doc_url: https://docs.album.solutions
  dev_url: https://gitlab.com/album-app/album-gui

extra:
  recipe-maintainers:
    - frauzufall
